[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
rand = { version = "0.8.5", default-features = false, features = [
    "alloc",
    "libc",
] }
rand_pcg = "0.3.1"

[dev-dependencies]
proptest = "1.5.0"
proptest-derive = "0.5.0"
