#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SCHEMA="${ROOT}/beeps-server/test/schema.sql"

(
    echo "-- WARNING: autogenerated by ${0:-}. Run that again to regenerate!"
    echo "--"
    echo "-- The purpose of this schema is to make setting up DBs in CI easier."
    echo "-- Don't use it in production environments; use migrations instead."
    echo
    pg_dump --schema-only --exclude-schema _sqlx_test
) > "$SCHEMA"
