name: CI

on:
  push:

env:
  CLICOLOR: 1

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.29.5

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev
      - run: cargo clippy -- --deny=warnings

  machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Machete
        uses: bnjbvr/cargo-machete@main

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: beeps
          POSTGRES_PASSWORD: beeps
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    env:
      DATABASE_URL: postgres://beeps:beeps@localhost:5432/beeps

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev

      # DB prep
      - run: cargo install sqlx-cli --no-default-features --features=postgres
      - run: sqlx migrate run --source beeps-server/migrations

      # Test
      - run: cargo test

  wasm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
          cache-directories: |
            target/wasm32-unknown-unknown
      - run: cargo install wasm-pack
      - run: wasm-pack build browser --out-dir $GITHUB_WORKSPACE/pkg
      - uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: pkg/*

  server-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # Build
      - run: cargo build --release --bin beeps-server

      # Container
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

  ui-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ui
      - run: bun run build
        working-directory: ui

  ui-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ui
      - run: bun run lint
        working-directory: ui

  ui-test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ui
      - run: bun run test:unit
        working-directory: ui

  ui-test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: |
            fonts-liberation fonts-noto-color-emoji glib-networking
            glib-networking-common glib-networking-services
            gsettings-desktop-schemas libaa1 libabsl20220623t64 libasound2t64
            libass9 libasyncns0 libatk-bridge2.0-0t64 libatk1.0-0t64 libatomic1
            libatspi2.0-0t64 libavc1394-0 libavcodec60 libavfilter9
            libavformat60 libavtp0 libavutil58 libblas3 libbluray2 libbs2b0
            libcaca0 libcairo-gobject2 libcairo-script-interpreter2 libcairo2
            libcdparanoia0 libchromaprint1 libcjson1 libcodec2-1.2 libcups2t64
            libdav1d7 libdbus-1-3 libdc1394-25 libdca0 libdecor-0-0
            libdirectfb-1.7-7t64 libdrm2 libdv4t64 libdvdnav4 libdvdread8t64
            libegl-mesa0 libegl1 libenchant-2-2 libepoxy0 libfaad2 libflac12t64
            libfluidsynth3 libfontconfig1 libfreeaptx0 libfreetype6 libgav1-1
            libgbm1 libgdk-pixbuf-2.0-0 libglib2.0-0t64 libgme0
            libgraphene-1.0-0 libgsm1 libgssdp-1.6-0
            libgstreamer-plugins-good1.0-0 libgstreamer1.0-0 libgtk-3-0t64
            libgtk-4-common libgupnp-1.6-0 libgupnp-igd-1.6-0 libharfbuzz0b
            libhwy1t64 libicu74 libiec61883-0 libimath-3-1-29t64
            libinstpatch-1.0-2 libjack-jackd2-0 libjpeg-turbo8 libjxl0.7
            liblapack3 liblc3-1 liblcms2-2 libldacbt-enc2 liblilv-0-0 liblrdf0
            libltc11 libmbedcrypto7t64 libmfx1 libmjpegutils-2.1-0t64
            libmodplug1 libmp3lame0 libmpcdec6 libmpeg2encpp-2.1-0t64
            libmpg123-0t64 libmplex2-2.1-0t64 libmysofa1 libneon27t64 libnice10
            libnspr4 libnss3 libopenal-data libopenal1 libopenexr-3-1-30
            libopenh264-7 libopenmpt0t64 libopenni2-0 liborc-0.4-0t64
            libpango-1.0-0 libpangocairo-1.0-0 libpipewire-0.3-0t64
            libplacebo338 libpng16-16t64 libpocketsphinx3 libpostproc57
            libproxy1v5 libpulse0 libqrencode4 libraptor2-0 librav1e0
            libraw1394-11 librist4 librsvg2-2 librubberband2 libsamplerate0
            libsbc1 libsdl2-2.0-0 libsecret-common libserd-0-0 libshine3
            libshout3 libsndfile1 libsndio7.0 libsord-0-0 libsoundtouch1
            libsoup-3.0-0 libsoup-3.0-common libsoxr0 libspa-0.2-modules
            libspandsp2t64 libspeex1 libsphinxbase3t64 libsratom-0-0
            libsrt1.5-gnutls libsrtp2-1 libssh-gcrypt-4 libsvtav1enc1d1
            libswresample4 libswscale7 libtag1v5 libtag1v5-vanilla libtheora0
            libtwolame0 libudfread0 libunibreak5 libv4l-0t64 libv4lconvert0t64
            libva-drm2 libva-x11-2 libva2 libvdpau1 libvidstab1.1
            libvisual-0.4-0 libvo-aacenc0 libvo-amrwbenc0 libvorbisenc2 libvpl2
            libwavpack1 libwayland-client0 libwayland-egl1 libwayland-server0
            libwebp7 libwebpdemux2 libwebrtc-audio-processing1 libwildmidi2
            libx11-6 libx11-xcb1 libx265-199 libxcb-shm0 libxcb-xkb1 libxcb1
            libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6
            libxkbcommon-x11-0 libxkbcommon0 libxml2 libxrandr2 libxrender1
            libxslt1.1 libxvidcore4 libyuv0 libzbar0t64 libzimg2 libzix-0-0
            libzvbi-common libzvbi0t64 libzxing3 ocl-icd-libopencl1
            session-migration timgm6mb-soundfont xfonts-encodings xfonts-utils
            xvfb
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ui
      - run: bunx playwright install --with-deps
        working-directory: ui
      - run: bun run test:e2e
        working-directory: ui
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/

  ui-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ui
      - run: bunx prettier --check src/
        working-directory: ui
